import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const errors=[];
try{
const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5180/japanMap/');await page.waitForFunction(()=>window.japanMap?.quality,null,{timeout:180000});await page.evaluate(()=>window.japanMap.quality('low'));await page.locator('.start__button').click();if(await page.locator('.menu__resume').isVisible())await page.locator('.menu__resume').click();
await fs.mkdir('screenshots/wp5',{recursive:true});
const arrival=await page.evaluate(()=>{const e=window.japanMap.engine,d=e.systems.find(s=>s.name==='DriveSystem'),s=e.systems.find(s=>s.name==='StillwaterVillage');e.stop();d.board();d.placeAt(-1266.5,416.6,Math.PI);d.alight();s.update(0);window.wp5Walk=(points)=>{const out=[];for(const [tx,tz] of points){let n=0;for(;n<1800;n++){const p=d.walker.position;if(Math.hypot(tx-p.x,tz-p.z)<.25)break;const angle=Math.atan2(tx-p.x,tz-p.z);d.ground.refresh(p.x,p.z,1/60);d.walker.step(1/60,{forward:1,right:0,jump:false,sprint:false},d,d.collision,angle);}out.push({target:[tx,tz],distance:Math.hypot(tx-d.walker.position.x,tz-d.walker.position.z),steps:n});}d.walkCamera.reset(d.walker);d.update(0,0);s.update(0);return out;};return {walking:d.walking,position:d.walker.position.toArray(),path:window.wp5Walk([[-1260,417],[-1255,417],[-1244,416],[-1244,411],[-1248.3,410.6]])};});
console.log('arrival',arrival);assert.ok(arrival.walking);for(const p of arrival.path)assert.ok(p.distance<.3,JSON.stringify(p));
await page.keyboard.press('Enter');const closed=await page.evaluate(()=>{const e=window.japanMap.engine,s=e.systems.find(s=>s.name==='StillwaterVillage');for(let i=0;i<180;i++)s.update(1/60);return{open:s.sluiceOpen,text:s.label.textContent,lever:s.lever.rotation.x};});assert.equal(closed.open,false);assert.match(closed.text,/Sluice closed/);assert.ok(closed.lever<0);
await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.japanMap.engine.systems.find(s=>s.name==='StillwaterVillage').sluiceOpen),true);
await page.evaluate(()=>{const e=window.japanMap.engine,d=e.systems.find(s=>s.name==='DriveSystem');window.wp5Walk([[-1244,411]]);d.walker.yaw=Math.PI;d.walkCamera.reset(d.walker);e.start();});await page.waitForTimeout(2500);await page.screenshot({path:'screenshots/wp5/interior.png'});
await page.evaluate(()=>window.japanMap.engine.stop());const pond=await page.evaluate(()=>window.wp5Walk([[-1244,411],[-1244,418],[-1257,417],[-1257,410],[-1257,398],[-1263,398]]));console.log('pond',pond);for(const p of pond)assert.ok(p.distance<.3,JSON.stringify(p));
await page.keyboard.press('Enter');await page.evaluate(()=>{const e=window.japanMap.engine,s=e.systems.find(s=>s.name==='StillwaterVillage');s.update(0);e.start();});await page.waitForTimeout(2500);assert.match(await page.locator('.settlement-prompt').innerText(),/River water/);await page.screenshot({path:'screenshots/wp5/pond-walk.png'});
await page.evaluate(()=>window.japanMap.engine.stop());const back=await page.evaluate(()=>{const d=window.japanMap.engine.systems.find(s=>s.name==='DriveSystem');const path=window.wp5Walk([[-1257,398],[-1257,410],[-1257,417],[-1260,417],[-1265,417]]);return {path,boarded:d.board(),range:d.vehicleRange()};});console.log('return',back);for(const p of back.path)assert.ok(p.distance<.3,JSON.stringify(p));assert.equal(back.boarded,true);
const net=await page.evaluate(()=>{const e=window.japanMap.engine,d=e.systems.find(s=>s.name==='DriveSystem');d.placeAt(784,1017,Math.PI/2);d.alight();return window.wp5Walk([[784,1016],[784,1008]]);});console.log('Net House',net);for(const p of net)assert.ok(p.distance<.3,JSON.stringify(p));await page.keyboard.press('Enter');await page.evaluate(()=>{const e=window.japanMap.engine,s=e.systems.find(s=>s.name==='StillwaterVillage');s.update(0);e.start();});await page.waitForTimeout(2500);assert.match(await page.locator('.settlement-prompt').innerText(),/net-menders/);await page.screenshot({path:'screenshots/wp5/net-house.png'});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{const s=window.japanMap.engine.systems.find(s=>s.name==='StillwaterVillage');s.update(0);});await page.waitForTimeout(1200);const touch=await page.locator('.settlement-prompt button').boundingBox();assert.ok(touch.height>=44);assert.ok(touch.x>=0&&touch.x+touch.width<=390);await page.screenshot({path:'screenshots/wp5/phone-inspect.png'});
assert.deepEqual(errors,[]);await fs.writeFile('screenshots/wp5/visit.json',JSON.stringify({arrival,pond,back,net,touch,errors},null,2));console.log('WP5 park, alight, mill, sluice, pond, board, Net House and phone Inspect passed.');
}finally{await browser.close();}
